apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x2bh14p2m-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x2bh14p2m-dotnet-basic-gitops