apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x2bh14p2m-dotnet-basic
  janus-idp.io/tekton: x2bh14p2m-dotnet-basic
  backstage.io/kubernetes-id: x2bh14p2m-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x2bh14p2m-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
